import { userConstants } from "../../constants/ActionTypes";


const initialState = {
    merchantList : [],
    page : 1,
    limit : 10,
    totalPage : 0,
    merchantDetail : {},
    accountDetail : {},
    mainAccount : {},
    type : "profile",
    modalIsOpen : false, 
    viewImage : "",
    apiDetails:{},
    public_key:"",
    secret_key:"",
    webhook_url:"",
    whitelisted_ips:[],
    showBalance:false,
    searchTerm : "",
    search_type:"",
    showFilter : false,
    startDate : new Date(),
    endDate : new Date(),
    fromDate: "",    
    toDate: "",  
    from:"",
    to:"",
    open_picker : false,
    loadRecords:false,
    merchantList:[],
    openApproveModal:false,
    openMerchantTypeModal :false,
    closeMerchantTypeModal:false,
    mcclist:[],
    clientList:[],
    entityList:[],
    mcc_name:"",
    mcc_code:"",
    mcc_id:"",
    client_type:"",
    client_id:"",
    entity_type:"",
    entity_id:"",
    filterList:false,
    accountActivationStatus:"",
    accountActivationStatusLabel:"",
    nodalAccountList:[],
    nodal_account_id:"",
    nodal_account_name:"",
    merchantId:"",
    webhookDetail:{},
    pan:"",
    openGenReportModal:false,
    con_report_id:"",
    bank_account_name:"",
    account_number:"",
    confirm_account_number:"",
    ifsc:"",
    bank_details:"",
    showBankDetailsForm:false,
    get_bank_details:"",
    get_account_number:"",
    get_ifsc:"",
    get_bank_account_name:"",
    edit_bank_details:"",
    edit_account_number:"",
    edit_confirm_account_number:"",
    edit_ifsc:"",
    edit_bank_account_name:"",
    account_id:"",
    editBankModal:false,
    bankAccountList:[],
    debitBankWhiteList:[],
    filter:"",
    reseller_id:"",
    reseller_name:"",
    isConnectedBanking:null,
    isConnectedBankingLabel:"",
    connectedBankingLimit:null,
    account_type:"",
    checkWhitelist:false,
    credit_whitelisting_count:0,
    debit_whitelisting_count:0,
    credit_whitelisting:true,
    debit_whitelisting:false,
    WhitelistType:"bank",
    debitUpiWhiteList:[],

    
};

export function payout_merchant(state = initialState, action) {
    switch (action.type) {          
        case userConstants.PAYOUT_MERCHANT:
            return {
                ...state,
                ...action.payload
            };          
        default:
            return state
    }
}