import React, { useEffect, useState } from "react";
import ApiGateway from "../../DataServices/DataServices";
import Loader from "../Loader";
import { useToasts } from "react-toast-notifications";
import { returnTimeZoneDate, textCapitalize } from "../../DataServices/Utils";
import Pagination from "../Pagination";
import cookie from "react-cookies";
import useRouteExist from "../../DataServices/useRouteExist";
const DownloadReportList = () => {
  const { addToast } = useToasts();
  const applyToast = (msg, type) => {
    return addToast(msg, { appearance: type });
  };

  const downloadReportRoute=useRouteExist(["admin-download-manager-signed-url"])
  const [pageno, setPageNo] = useState(1);
  const [limit, setLimit] = useState(10);
  const [recordsLength, setrecordLength] = useState([]);
  const [state, setState] = useState({
    loading: false,
    downloadReportList: [],
  });
  useEffect(() => {
    getDownloadReportList();
  }, []);

  const getDownloadReportList = () => {
    setState((prevState) => ({
      ...prevState,
      loading: true,
    }));
    ApiGateway.get(`/payout/admin/downloadmanager/list`, function (response) {
      if (response.success) {
        setState((prevState) => ({
          ...prevState,
          downloadReportList: response?.data?.downloadManagers,
          loading: false,
        }));
      } else {
        setState((prevState) => ({
          ...prevState,
          loading: false,
        }));
        applyToast(response.message);
      }
    });
  };

  const handleDownload1 = (file) => {
    const signedUrl = file?.s3?.location || file?.s3?.location;
    const link = document.createElement("a");
    link.href = signedUrl;
    link.download = "Report.pdf";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownload = (file) => {
    ApiGateway.get(
      `/payout/admin/downloadmanager/get-signed-url?fileId=${file}`,
      function (response) {
        if (response.success) {
          const signedUrl = response.data;
          const link = document.createElement("a");
          link.href = signedUrl;
          link.download = "Report.";
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          applyToast("File Downloaded Successfully","success");
        } else {
          applyToast(response.message);
        }
      }
    );
  };

  return (
    <>
      <div className="tab-content">
        {state.loading && <Loader />}
        <div className="col-xs-12 p-0">
          <div className="table-responsive">
            <table className="table  table_customization">
              <thead>
                <tr>
                  <th>S.No</th>
                  <th>Created At</th>
                  <th>Generated By</th>
                  <th>Category</th>
                  <th>Type</th>
                  <th>Status</th>
              {downloadReportRoute &&  <th>Download</th>}   
                </tr>
              </thead>
              <tbody>
                {state.downloadReportList?.map((list, i) => {
                  return (
                    <tr className="payout_merchant" key={"list" + i}>
                      <td>{(pageno - 1) * limit + (i + 1)}</td>
                      <td>
                        {list?.generatedDate	
                          ? returnTimeZoneDate(list?.generatedDate	)
                          : "-"}
                      </td>
                      <td>
                        {list?.createdBy?.name
                          ? textCapitalize(list?.createdBy?.name.toLowerCase())
                          : "-"}
                      </td>
                      <td>{list?.filePurpose ? list?.filePurpose : ""}</td>
                      <td>{list?.fileType ? list?.fileType : ""}</td>
                      <td>
                        <span className="label_edit">
                          {list?.status ? textCapitalize(list?.status) : "-"}
                        </span>
                      </td>
                      {downloadReportRoute && <td>
                        <span
                          className="label_edit pointer-cursor"
                          onClick={() =>
                            handleDownload(list?.fileId)
                          }
                        >
                          Download
                        </span>
                      </td>}
                     
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          <div className="table-bottom-content">
            <Pagination
              handle={getDownloadReportList}
              list={recordsLength}
              currentpage={pageno}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default DownloadReportList;
